language: rust

notifications:
  webhooks: http://build.servo.org:54856/travis

matrix:
  include:
    - rust: 1.21.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: FEATURES="--features unstable"

script:
  - cargo build $FEATURES
  - cargo test --verbose $FEATURES
