[package]
name = "euclid"
version = "0.1.2"
authors = ["The Servo Project Developers"]
description = "Geometry primitives"
documentation = "http://doc.servo.org/euclid/"
license = "MIT / Apache-2.0"

[dependencies]
rustc-serialize = "0.3.2"
rand = "0.3.7"
num = "0.1.24"
log = "0.3.1"
serde = "*"
serde_macros = "*"
