[package]

name = "geom"
version = "0.1.0"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/geom/"

[dependencies]
rustc-serialize = "0.3.2"
rand = "0.3.7"
num = "0.1.24"
log = "0.3.1"
