name: CI

on:
  push:
    branches: [auto]
  pull_request:
  workflow_dispatch:

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--features serde"]
        version: ["1.34.0", "stable", "beta", "nightly"]
        include:
          - version: stable
            features: --features mint
          - version: stable
            features: --no-default-features --features libm
          - version: nightly
            features: --features unstable
          - version: nightly
            features: --features unstable,serde
        
    steps:
      - uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}
          override: true

      - name: Cargo build
        run: cargo build ${{ matrix.features }}

      - name: Cargo test
        run: cargo test ${{ matrix.features }}
        env:
          RUST_BACKTRACE: 1

      - name: bytemuck
        run: cargo check --features bytemuck

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    needs:
      - "linux-ci"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
